ARG CENTOS_DOCKER_LABEL
ARG CENTOS_DOCKER_TAG

FROM ${CENTOS_DOCKER_LABEL}:${CENTOS_DOCKER_TAG}

ARG BUNDLER_VERSION=1.17.2
ENV RUBY_VERSION 2.5.5

RUN yum update -y \
  && yum install -y \
    autoconf \
    automake \
    bison \
    bzip2 \
    git-core \
    libyaml-devel \
    libffi-devel \
    libtool \
    openssl \
    openssl-devel \
    patch \
    readline \
    readline-devel \
    sudo \
    zlib \
    zlib-devel \
  && yum clean all

RUN git clone git://github.com/rbenv/rbenv.git /usr/local/rbenv \
    &&  git clone git://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build \
    &&  git clone git://github.com/jf/rbenv-gemset.git /usr/local/rbenv/plugins/rbenv-gemset \
    &&  /usr/local/rbenv/plugins/ruby-build/install.sh

ENV RBENV_ROOT /usr/local/rbenv

ENV CONFIGURE_OPTS --disable-install-doc

ENV PATH /usr/local/rbenv/bin:/usr/local/rbenv/shims:$PATH

RUN rbenv install -v ${RUBY_VERSION} && \
  rbenv global ${RUBY_VERSION}

RUN gem install bundler -v ${BUNDLER_VERSION}

RUN yum remove -y autoconf automake libtool bison

CMD [ "irb" ]
