ARG CENTOS_DOCKER_LABEL
ARG CENTOS_DOCKER_TAG

FROM ${CENTOS_DOCKER_LABEL}:${CENTOS_DOCKER_TAG}

ARG BUNDLER_VERSION=1.17.2
ENV RUBY_VERSION 2.5.5

RUN yum install -y epel-release && \
    yum update -y

RUN yum install -y \
    autoconf \
    automake \
    bison \
    bzip2 \
    git-core \
    libyaml-devel \
    libffi-devel \
    libtool \
    openssl \
    openssl-devel \
    patch \
    readline \
    readline-devel \
    sudo \
    zlib \
    zlib-devel

RUN git clone git://github.com/rbenv/rbenv.git /usr/local/rbenv \
    &&  git clone git://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build \
    &&  git clone git://github.com/jf/rbenv-gemset.git /usr/local/rbenv/plugins/rbenv-gemset \
    &&  /usr/local/rbenv/plugins/ruby-build/install.sh
ENV PATH /usr/local/rbenv/bin:$PATH
ENV RBENV_ROOT /usr/local/rbenv

RUN echo 'export RBENV_ROOT=/usr/local/rbenv' >> /etc/profile.d/rbenv.sh \
    &&  echo 'export PATH=/usr/local/rbenv/bin:$PATH' >> /etc/profile.d/rbenv.sh \
    &&  echo 'eval \"$(rbenv init -)\"' >> /etc/profile.d/rbenv.sh

RUN echo 'export RBENV_ROOT=/usr/local/rbenv' >> /root/.bashrc \
    &&  echo 'export PATH=/usr/local/rbenv/bin:$PATH' >> /root/.bashrc \
    &&  echo 'eval \"$(rbenv init -)\"' >> /root/.bashrc

ENV CONFIGURE_OPTS --disable-install-doc
ENV PATH /usr/local/rbenv/bin:/usr/local/rbenv/shims:$PATH

RUN rbenv install -v ${RUBY_VERSION} && \
  rbenv global ${RUBY_VERSION}

RUN gem install bundler -v ${BUNDLER_VERSION}

RUN yum remove -y autoconf automake libtool bison

CMD [ "irb" ]
